### ISSUE TITLE
Modify service name to `CypherCrescent Build Service`

### ISSUE THREAD

**Issue by geekhybrid** [Osoba001/CCLSelfService#2]
https://github.com/Osoba001/CCLSelfService/blob/ed90eae51fe987683ee03dc0246a795a816eeec1/Cyphercrescent.SelfService.BuildBackgroundService/Program.cs#L25

**See examples**
![image](https://user-images.githubusercontent.com/39003759/216609223-fbc94a61-089a-44e6-8b0c-2c2e506fde20.png)

**Comment by Osoba001** [comment]
Completed
